config/routes.rb
Rails.application.routes.draw do
  get 'stats/index'

  get 'comments/new'
  post 'comments/create', as: "comments"

  get 'articles/show'
  root to: 'author#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author
  has_many :comments

  def self.all_names
    all.map do |art|
      art.name
    end
  end

  def self.five_longest_article_names
    all.sort_by do |art|
      art.name
    end.last(5).map do |art|
      art.name
    end
  end

  def self.articles_with_names_less_than_20_char
    select do |art|
      art.name.length < 20
    end
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :articles

  def self.generate_authors(count=1000)
    count.times do
      Fabricate(:author)
    end
    first.articles << Article.create(name: "some commenter", body: "some body")
  end

  def self.most_prolific_writer
    all.sort_by{|a| a.articles.count }.last
  end

  def self.with_most_upvoted_article
    all.sort_by do |auth|
      auth.articles.sort_by do |art|
        art.upvotes
      end.last
    end.last.name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params["format"])
  end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController

  def index
    @authors = Author.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @article = Article.find(params[:article])
    @comment = Comment.new
  end

  def create
    article = Article.find(params[:comment][:article].to_i)
    article.comments << Comment.create(author: params[:comment][:author], body: params[:comment][:body])
    redirect_to articles_show_path(article)
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @five_longest_article_names = Article.five_longest_article_names
    @prolific_author = Author.most_prolific_writer
    @author_with_most_upvoted_article = Author.with_most_upvoted_article
    @article_names = Article.all_names
    @short_articles = Article.articles_with_names_less_than_20_char
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/articles/show.html.erb
<h1>Terrible article show page</h1>
<h3><%= @article.name %></h1>

<p> Article body: <%= @article.body %></p>

<h2>Comments section</h2>
<p>
  <% @article.comments.each do |com| %>
    <%= com.body.html_safe %>
  <% end %>
</p>

<%= link_to "New Comment", comments_new_path(article: @article.id) %>

app/views/author/index.html.erb
<h1> This is a terrible authors index page. One of the worst ever. </h1>

<nav style="background-color: #9AEEE8">
  <%= link_to "Stats", stats_index_path %>
</nav>

<div class="author">
  <% @authors.each do |author| %>

      <h2>My name is <%= author.name %></h2>
      <% author.articles.each do |art| %>
        <p>I wrote: <span style="text-decoration: underline"><%= link_to art.name, articles_show_path(art) %> </span></p>
      <% end %>

  <% end %>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br>

  <%= f.label :body %>
  <%= f.text_area :body, size: "60x12" %>

  <%= f.hidden_field :article, value: @article.id %>
  
  <%= f.submit "Create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stats/index.html.erb
<h1>Some of the most inefficient ActiveRecord Querying ever.</h1>

<div class="stats-section">
  <div>Most prolific author: <%= @prolific_author.name %> </div>
  <div>Author with most upvoted article: <%= @author_with_most_upvoted_article %> </div>
  <p style="text-decoration: underline">Five longest article names:</p>
  <% @five_longest_article_names.each do |name| %>
    <li> <%= name %> </li>
  <% end %>

  <p style="text-decoration: underline">List of all the article names (TOO LONG)</p>
  <% @article_names.each do |name| %>
    <li><%= name %></li>
  <% end %>
</div>